version: "3.8"
services:
  frontend-hook:
    build: .
    ports:
      - "127.0.0.1:7979:80"   # HTTP через Nginx на хостовом 7979
    environment:
      - VITE_API_URL=/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # ваш конфиг nginx внутри контейнера
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

# Удалены публикация 443 и монтирование SSL, так как SSL обрабатывает внешний Nginx-прокси
