services:
  frontend_dockM:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:80" # вот тут другой внешний порт
    environment:
      - VITE_API_URL=http://94.228.120.140:4006 # тестовый бэкенд
