version: "3.8"
services:
  frontend-hook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7979:80" # только HTTP на локальном 7979
    environment:
      - VITE_API_URL=/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # единственный nginx-конфиг
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
