version: "3.8"
services:
  frontend-hook:
    build: .
    ports:
      - "127.0.0.1:7979:80" # HTTP на локальном 7979
      - "443:443" # HTTPS на стандартном 443
    environment:
      - VITE_API_URL=/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # кастомный nginx-конфиг
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # certbot-сертификаты
      - /etc/letsencrypt/live/app.denta-rell.ru/:/etc/nginx/certs/:ro
