version: "3.8"
services:
  frontend-hook:
    build: .
    ports:
      - "127.0.0.1:7979:80" # HTTP на локальном 7979
    environment:
      - VITE_API_URL=/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # nginx-конфиг внутри контейнера
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # Вся папка с сертификатами
      - /etc/letsencrypt/live/app.denta-rell.ru/:/etc/nginx/certs/:ro
