version: "3.8"
services:
  frontend_test:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"
    ports:
      - "8082:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.test.conf:/etc/nginx/conf.d/default.conf:ro
