version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "127.0.0.1:7979:80"
      - "443:443"
    environment:
      # относительный путь, чтобы всё шло через Nginx
      - VITE_API_URL=/api
    extra_hosts:
      # добавляем алиас host.docker.internal → IP хоста на Linux
      - "host.docker.internal:host-gateway"
    volumes:
      # ваш конфиг nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # SSL-сертификаты
      - /etc/letsencrypt/live/app.denta-rell.ru/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/app.denta-rell.ru/privkey.pem:/etc/nginx/certs/privkey.pem:ro

volumes:
  postgres_data:
  whatsapp-session:
