version: "3.8"
services:
  frontend_hookah:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80" # HTTP на локальном 8080
    environment:
      - VITE_API_URL=http://94.228.120.140:4004
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # nginx-конфиг внутри контейнера
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

      # Вся папка с сертификатами
      - /etc/letsencrypt/live/berlooga.ru/:/etc/nginx/certs/:ro
