  # Тестовый стенд
  services:
    frontend_testt:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8081:80"                 # вот тут другой внешний порт
      environment:
        - VITE_API_URL=http://localhost:4002  # тестовый бэкенд