# Тестовый стенд
services:
  frontend_test-psy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80" # вот тут другой внешний порт
    environment:
      - VITE_API_URL=http://94.228.120.140:4006 # тестовый бэкенд
