version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_URL=http://localhost:4000
    volumes:
      # собственный конфиг nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

      # сертификаты от Let's Encrypt
      - /etc/letsencrypt/live/app.denta-rell.ru/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/app.denta-rell.ru/privkey.pem:/etc/nginx/certs/privkey.pem:ro
